name: labar

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true
    
scripts:
  analyze:
    run: flutter analyze
    description: Run static analysis on all packages
    
  format:
    run: dart format .
    description: Format all Dart files
    
  clean:
    run: flutter clean
    description: Clean all packages
    
  get:
    run: flutter pub get
    description: Get dependencies for all packages
    
  build:runner:
    run: dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner for code generation
    exec:
      concurrency: 1
      
  watch:
    run: dart run build_runner watch --delete-conflicting-outputs
    description: Watch and run build_runner for code generation
    exec:
      concurrency: 1
