-- Migration to complete user deletion fixes
-- Addressing constraints in waybills and applications that were missed in previous fixes

-- 1. Fix Waybills Deletion Constraints
-- Make created_by nullable and set to NULL when the user is deleted
ALTER TABLE public.waybills ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE public.waybills DROP CONSTRAINT IF EXISTS waybills_created_by_fkey;
-- Note: the actual name might be waybills_created_by_fkey or generated by postgres
-- We try to catch both common naming patterns
DO $$ 
BEGIN
    -- Drop the constraint if it exists (try common names)
    ALTER TABLE public.waybills DROP CONSTRAINT IF EXISTS waybills_created_by_fkey;
    -- For references added without explicit name, Postgres usually names them "tablename_columnname_fkey"
    ALTER TABLE public.waybills DROP CONSTRAINT IF EXISTS waybills_created_by_id_fkey;
END $$;

-- Search for any constraint on waybills(created_by) and drop it
DO $$
DECLARE
    const_name TEXT;
BEGIN
    FOR const_name IN 
        SELECT conname 
        FROM pg_constraint 
        WHERE conrelid = 'public.waybills'::regclass 
        AND confrelid = 'auth.users'::regclass
        AND conkey @> (SELECT array_agg(attnum) FROM pg_attribute WHERE attrelid = 'public.waybills'::regclass AND attname = 'created_by')
    LOOP
        EXECUTE 'ALTER TABLE public.waybills DROP CONSTRAINT ' || const_name;
    END LOOP;
END $$;

ALTER TABLE public.waybills ADD CONSTRAINT waybills_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;


-- 2. Fix Applications User ID Deletion Constraints
-- When a user (farmer) is deleted, we want their application to be deleted as well
DO $$
DECLARE
    const_name TEXT;
BEGIN
    FOR const_name IN 
        SELECT conname 
        FROM pg_constraint 
        WHERE conrelid = 'public.applications'::regclass 
        AND confrelid = 'auth.users'::regclass
        AND conkey @> (SELECT array_agg(attnum) FROM pg_attribute WHERE attrelid = 'public.applications'::regclass AND attname = 'user_id')
    LOOP
        EXECUTE 'ALTER TABLE public.applications DROP CONSTRAINT ' || const_name;
    END LOOP;
END $$;

ALTER TABLE public.applications ADD CONSTRAINT applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- 3. Also check if there are any other references to auth.users that might block deletion
-- Check farmer_designation if it exists (it was mentioned in code but definition not found in migrations)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'farmer_designation') THEN
        -- If it references users directly, fix it. But based on Edge Function it references applications.
        -- We'll just ensure it has cascades to applications if it doesn't already.
        ALTER TABLE public.farmer_designation DROP CONSTRAINT IF EXISTS farmer_designation_application_fkey;
        ALTER TABLE public.farmer_designation ADD CONSTRAINT farmer_designation_application_fkey FOREIGN KEY (application) REFERENCES public.applications(id) ON DELETE CASCADE;
    END IF;
END $$;
